[metadata]
name = dipster_bare
version = 0.1.0
author = Tim Craig
author_email = tim.craig@uantwerpen.be
description = Self-contained machine learning library for time-resolved electron tomography (no tomobase / tomo-ndt / cupy dependencies)
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/EMAT-tomography/dipster
license = GPL3.0
classifier =
    Programming Language :: Python :: 3
    License :: OSI Approved :: GPL3.0 License
    Operating System :: OS Independent

[options]
packages = find:
include_package_data = True
python_requires = >=3.10
install_requires =
    numpy
    pandas
    blosc
    scikit-image
    kornia
    wandb
    tqdm
    ray[tune]
    optuna
    plotly
    # torch / torchvision: install the CUDA build that matches your GPU (see README)
    # tomosipo, astra-toolbox: install via conda (see README) -- not pip-installable
